### ISSUE TITLE
Offer a way to re-check when browser path change

### ISSUE THREAD

**Issue by icastillejogomez** [aruniverse/adblock-detect-react#18] opened 2021-12-23 01:14 UTC
Pass config object to hook to re-check when browser urls changes.

When I make a route change with next-router system and the destination path is not in the adblock whitelist this module does not catch it

**Comment by aruniverse** [comment] 2021-12-23 04:13
Hi, I'm not sure if I follow. Could you possibly create a sample on [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/) demonstrating the issue? There is no _"whitelist"_.

**Comment by domis4** [comment] 2022-01-11 15:30
@icastillejogomez i use it with nextjs with no problem. Make sure it is part of your route component, not the global one. If its you global one you would add to need the key property like:

``key={router.asPath}``

**Comment by aruniverse** [comment] 2022-01-28 13:47
Closing this issue since it's been over a month since the last update from @icastillejogomez and @domis4 has provided a workaround solution. If this still appears to be an actual issue, we can reopen it; but please provide a reproducible sample.

**Closed by aruniverse** 2022-01-28 13:47 UTC
